[package]
name = "rust_exercises"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
dotenv = "0.15.0"
clap = { version = "4.5.13", features = ["derive", "cargo", "unicode", "wrap_help"] }
solana-sdk = "2.0.5"
solana-client = "2.0.5"
serde_json = "1.0.122"
